[package]
name = "orx-local-search"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
orx-meta = { version = "1.1.0" }
orx-self-or = { version = "1.2.0" }


[dev-dependencies]
orx-iterable = { version = "1.3.0" }
